# Generated by Django 5.2.14 on 2026-06-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone_no',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='zip_code',
            new_name='zipCode',
        ),
    ]
